<?php

namespace app\modules\api\components;
use yii\rest\Controller as RestController;
use yii\web\Response;
use yii\filters\Cors;

class Controller extends RestController
{

	public function beforeAction( $action ) {

		$this->enableCsrfValidation = false;

		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}


	public function behaviors()
	{
		$behaviors = parent::behaviors();

		// remove authentication filter
		$auth = $behaviors['authenticator'];
		unset($behaviors['authenticator']);

		// add CORS filter
        $behaviors['corsFilter'] = [
	        'class' => Cors::class,
	        'cors' => \Yii::$app->controller->module->params['cors']
        ];

        // re-add authentication filter
		$behaviors['authenticator'] = $auth;
		// avoid authentication on CORS-pre-flight requests (HTTP OPTIONS method)
		$behaviors['authenticator']['except'] = ['options'];

		return $behaviors;
	}

	public function actionOptions ()
	{
		if (\Yii::$app->getRequest()->getMethod() !== 'OPTIONS') {
			\Yii::$app->getResponse()->setStatusCode(405);
		}
		$options = $this->verbs();
		\Yii::$app->getResponse()->getHeaders()->set('Allow', implode(', ', $options));
	}

}